### ISSUE TITLE
Broken on PyPi

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc-timelines#3]
Installing this plugin from pypi, using 

```
pip install twarc-timeline-archive
```

fails, with 

```
timeline_archive  † Warning: could not load plugin.
```
```
twarc2 timeline_archive --help

Warning: entry point could not be loaded. Contact its author for help.

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.7.5/envs/twarc/lib/python3.7/site-packages/click_plugins/core.py", line 37, in decorator
    group.add_command(entry_point.load())
  File "/home/user/.pyenv/versions/3.7.5/envs/twarc/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/user/.pyenv/versions/3.7.5/envs/twarc/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'twarc_timeline_archive'
```

The version on pypi is `0.1.0`, but the one here is `v0.0.5`

**Comment by edsu** [comment]
weird it just installed ok for me:

```
➜  ~ pip install twarc-timeline-archive
Collecting twarc-timeline-archive
  Downloading twarc-timeline-archive-0.1.0.tar.gz (2.3 kB)
Requirement already satisfied: twarc>=2.0.8 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from twarc-timeline-archive) (2.8.3)
Requirement already satisfied: click<9,>=7 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from twarc>=2.0.8->twarc-timeline-archive) (8.0.3)
Requirement already satisfied: click-config-file>=0.6 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from twarc>=2.0.8->twarc-timeline-archive) (0.6.0)
Requirement already satisfied: click-plugins>=1 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from twarc>=2.0.8->twarc-timeline-archive) (1.1.1)
Requirement already satisfied: tqdm>=4.62 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from twarc>=2.0.8->twarc-timeline-archive) (4.62.3)
Requirement already satisfied: python-dateutil>=2.8 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from twarc>=2.0.8->twarc-timeline-archive) (2.8.2)
Requirement already satisfied: humanize>=3.9 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from twarc>=2.0.8->twarc-timeline-archive) (3.13.1)
Requirement already satisfied: requests-oauthlib>=1.3 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from twarc>=2.0.8->twarc-timeline-archive) (1.3.0)
Requirement already satisfied: configobj>=5.0.6 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from click-config-file>=0.6->twarc>=2.0.8->twarc-timeline-archive) (5.0.6)
Requirement already satisfied: six in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from configobj>=5.0.6->click-config-file>=0.6->twarc>=2.0.8->twarc-timeline-archive) (1.16.0)
Requirement already satisfied: requests>=2.0.0 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from requests-oauthlib>=1.3->twarc>=2.0.8->twarc-timeline-archive) (2.27.1)
Requirement already satisfied: oauthlib>=3.0.0 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from requests-oauthlib>=1.3->twarc>=2.0.8->twarc-timeline-archive) (3.1.1)
Requirement already satisfied: idna<4,>=2.5 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=1.3->twarc>=2.0.8->twarc-timeline-archive) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=1.3->twarc>=2.0.8->twarc-timeline-archive) (2.0.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=1.3->twarc>=2.0.8->twarc-timeline-archive) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in ./.pyenv/versions/3.10.1/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=1.3->twarc>=2.0.8->twarc-timeline-archive) (2021.10.8)
Using legacy 'setup.py install' for twarc-timeline-archive, since package 'wheel' is not installed.
Installing collected packages: twarc-timeline-archive
    Running setup.py install for twarc-timeline-archive ... done
Successfully installed twarc-timeline-archive-0.1.0
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/Users/edsummers/.pyenv/versions/3.10.1/bin/python3.10 -m pip install --upgrade pip' command.
```

I forgot to push a tag for 0.1.0 (and no longer have the laptop where it was). I'll push up v v0.1.1 and can work with that going forward to resolve this issue.

**Comment by edsu** [comment]
Does v0.1.1 work any better? I would guess not seeing as I didn't change anything other than the version and the README.

**Comment by igorbrigadir** [comment]
No, that also fails but i think i know what the error is, i broke twarc-csv in the exact same way: it's the module name in `setup.py` - fixed in #4

**Comment by edsu** [comment]
Does v0.1.2 work?

**Comment by igorbrigadir** [comment]
Yep! That worked!
